"""star schema with mandatory provenance

Revision ID: 3bf5dacdb8da
Revises: 
Create Date: 2026-09-08 07:22:25.980302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf5dacdb8da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_airline',
    sa.Column('airline_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airline_name', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('is_aggregate', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('airline_id', name=op.f('pk_dim_airline')),
    sa.UniqueConstraint('airline_name', name=op.f('uq_dim_airline_airline_name'))
    )
    op.create_index(op.f('ix_dim_airline_is_aggregate'), 'dim_airline', ['is_aggregate'], unique=False)
    op.create_table('dim_airport',
    sa.Column('airport_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=True),
    sa.Column('icao_code', sa.String(length=8), nullable=True),
    sa.Column('airport_name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('is_international', sa.Boolean(), nullable=True),
    sa.Column('resolution_method', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('airport_id', name=op.f('pk_dim_airport')),
    sa.UniqueConstraint('airport_name', 'country', name='airport_name_country')
    )
    op.create_index(op.f('ix_dim_airport_country'), 'dim_airport', ['country'], unique=False)
    op.create_index(op.f('ix_dim_airport_iata_code'), 'dim_airport', ['iata_code'], unique=False)
    op.create_index(op.f('ix_dim_airport_icao_code'), 'dim_airport', ['icao_code'], unique=False)
    op.create_table('dim_period',
    sa.Column('period_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_label', sa.String(length=16), nullable=False),
    sa.Column('period_kind', sa.String(length=8), nullable=False),
    sa.Column('calendar_year', sa.Integer(), nullable=False),
    sa.Column('calendar_month', sa.Integer(), nullable=True),
    sa.Column('fiscal_year_start', sa.Integer(), nullable=True),
    sa.Column('sort_key', sa.Integer(), nullable=False),
    sa.CheckConstraint("period_kind IN ('MONTH','FISCAL','ANNUAL')", name=op.f('ck_dim_period_period_kind_known')),
    sa.CheckConstraint('calendar_month IS NULL OR calendar_month BETWEEN 1 AND 12', name=op.f('ck_dim_period_month_in_range')),
    sa.PrimaryKeyConstraint('period_id', name=op.f('pk_dim_period')),
    sa.UniqueConstraint('period_label', name=op.f('uq_dim_period_period_label'))
    )
    op.create_index(op.f('ix_dim_period_calendar_year'), 'dim_period', ['calendar_year'], unique=False)
    op.create_index(op.f('ix_dim_period_sort_key'), 'dim_period', ['sort_key'], unique=False)
    op.create_table('forecast',
    sa.Column('forecast_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grain', sa.Enum('AIRPORT', 'AIRLINE', name='grain_enum'), nullable=False),
    sa.Column('entity_key', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.Enum('INTERNATIONAL', 'DOMESTIC', 'TOTAL', name='direction_enum'), nullable=False),
    sa.Column('period_label', sa.String(length=16), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('predicted_kg', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('lower_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('upper_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('backtest_mape', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('forecast_id', name=op.f('pk_forecast')),
    sa.UniqueConstraint('grain', 'entity_key', 'direction', 'period_label', 'model', name='forecast_natural_key')
    )
    op.create_index(op.f('ix_forecast_entity_key'), 'forecast', ['entity_key'], unique=False)
    op.create_table('ingest_run',
    sa.Column('ingest_run_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('facts_loaded', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ingest_run_id', name=op.f('pk_ingest_run'))
    )
    op.create_table('anomaly',
    sa.Column('anomaly_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grain', sa.Enum('AIRPORT', 'AIRLINE', name='grain_enum'), nullable=False),
    sa.Column('entity_key', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.Enum('INTERNATIONAL', 'DOMESTIC', 'TOTAL', name='direction_enum'), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('observed_kg', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('expected_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('deviation_pct', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('evidence_fact_ids', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH')", name=op.f('ck_anomaly_severity_known')),
    sa.ForeignKeyConstraint(['period_id'], ['dim_period.period_id'], name=op.f('fk_anomaly_period_id_dim_period')),
    sa.PrimaryKeyConstraint('anomaly_id', name=op.f('pk_anomaly')),
    sa.UniqueConstraint('grain', 'entity_key', 'direction', 'period_id', 'method', name='anomaly_natural_key')
    )
    op.create_index(op.f('ix_anomaly_entity_key'), 'anomaly', ['entity_key'], unique=False)
    op.create_table('source_document',
    sa.Column('source_document_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doc_key', sa.String(length=64), nullable=False),
    sa.Column('publisher', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('media_type', sa.String(length=64), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('raw_path', sa.Text(), nullable=True),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("source_url NOT ILIKE '%%api-key=%%'", name=op.f('ck_source_document_no_credential_in_url')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.ingest_run_id'], name=op.f('fk_source_document_ingest_run_id_ingest_run')),
    sa.PrimaryKeyConstraint('source_document_id', name=op.f('pk_source_document')),
    sa.UniqueConstraint('doc_key', name=op.f('uq_source_document_doc_key'))
    )
    op.create_index(op.f('ix_source_document_publisher'), 'source_document', ['publisher'], unique=False)
    op.create_table('trend',
    sa.Column('trend_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grain', sa.Enum('AIRPORT', 'AIRLINE', name='grain_enum'), nullable=False),
    sa.Column('entity_key', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.Enum('INTERNATIONAL', 'DOMESTIC', 'TOTAL', name='direction_enum'), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('tonnage_kg', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('yoy_pct', sa.Float(), nullable=True),
    sa.Column('mom_pct', sa.Float(), nullable=True),
    sa.Column('cagr_pct', sa.Float(), nullable=True),
    sa.Column('share_of_total', sa.Float(), nullable=True),
    sa.Column('share_shift_pp', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['dim_period.period_id'], name=op.f('fk_trend_period_id_dim_period')),
    sa.PrimaryKeyConstraint('trend_id', name=op.f('pk_trend')),
    sa.UniqueConstraint('grain', 'entity_key', 'direction', 'period_id', name='trend_natural_key')
    )
    op.create_index(op.f('ix_trend_entity_key'), 'trend', ['entity_key'], unique=False)
    op.create_table('fact_cargo_movement',
    sa.Column('fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grain', sa.Enum('AIRPORT', 'AIRLINE', name='grain_enum'), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=True),
    sa.Column('airline_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Enum('INTERNATIONAL', 'DOMESTIC', 'TOTAL', name='direction_enum'), nullable=False),
    sa.Column('tonnage_kg', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('prior_year_tonnage_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('reported_change_pct', sa.Float(), nullable=True),
    sa.Column('publisher', sa.String(length=32), nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=False),
    sa.Column('resolution_confidence', sa.Float(), nullable=True),
    sa.Column('resolution_method', sa.String(length=64), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("(grain = 'AIRPORT' AND airport_id IS NOT NULL) OR (grain = 'AIRLINE' AND airline_id IS NOT NULL)", name=op.f('ck_fact_cargo_movement_grain_has_its_dimension')),
    sa.CheckConstraint('tonnage_kg >= 0', name=op.f('ck_fact_cargo_movement_tonnage_non_negative')),
    sa.ForeignKeyConstraint(['airline_id'], ['dim_airline.airline_id'], name=op.f('fk_fact_cargo_movement_airline_id_dim_airline')),
    sa.ForeignKeyConstraint(['airport_id'], ['dim_airport.airport_id'], name=op.f('fk_fact_cargo_movement_airport_id_dim_airport')),
    sa.ForeignKeyConstraint(['period_id'], ['dim_period.period_id'], name=op.f('fk_fact_cargo_movement_period_id_dim_period')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.source_document_id'], name=op.f('fk_fact_cargo_movement_source_document_id_source_document')),
    sa.PrimaryKeyConstraint('fact_id', name=op.f('pk_fact_cargo_movement')),
    sa.UniqueConstraint('grain', 'period_id', 'airport_id', 'airline_id', 'direction', 'publisher', name='fact_natural_key')
    )
    op.create_index(op.f('ix_fact_cargo_movement_airline_id'), 'fact_cargo_movement', ['airline_id'], unique=False)
    op.create_index(op.f('ix_fact_cargo_movement_airport_id'), 'fact_cargo_movement', ['airport_id'], unique=False)
    op.create_index(op.f('ix_fact_cargo_movement_grain'), 'fact_cargo_movement', ['grain'], unique=False)
    op.create_index(op.f('ix_fact_cargo_movement_publisher'), 'fact_cargo_movement', ['publisher'], unique=False)
    op.create_index('ix_fact_period_grain', 'fact_cargo_movement', ['period_id', 'grain'], unique=False)
    op.create_table('insight',
    sa.Column('insight_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('anomaly_id', sa.BigInteger(), nullable=True),
    sa.Column('citations', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomaly.anomaly_id'], name=op.f('fk_insight_anomaly_id_anomaly')),
    sa.PrimaryKeyConstraint('insight_id', name=op.f('pk_insight'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insight')
    op.drop_index('ix_fact_period_grain', table_name='fact_cargo_movement')
    op.drop_index(op.f('ix_fact_cargo_movement_publisher'), table_name='fact_cargo_movement')
    op.drop_index(op.f('ix_fact_cargo_movement_grain'), table_name='fact_cargo_movement')
    op.drop_index(op.f('ix_fact_cargo_movement_airport_id'), table_name='fact_cargo_movement')
    op.drop_index(op.f('ix_fact_cargo_movement_airline_id'), table_name='fact_cargo_movement')
    op.drop_table('fact_cargo_movement')
    op.drop_index(op.f('ix_trend_entity_key'), table_name='trend')
    op.drop_table('trend')
    op.drop_index(op.f('ix_source_document_publisher'), table_name='source_document')
    op.drop_table('source_document')
    op.drop_index(op.f('ix_anomaly_entity_key'), table_name='anomaly')
    op.drop_table('anomaly')
    op.drop_table('ingest_run')
    op.drop_index(op.f('ix_forecast_entity_key'), table_name='forecast')
    op.drop_table('forecast')
    op.drop_index(op.f('ix_dim_period_sort_key'), table_name='dim_period')
    op.drop_index(op.f('ix_dim_period_calendar_year'), table_name='dim_period')
    op.drop_table('dim_period')
    op.drop_index(op.f('ix_dim_airport_icao_code'), table_name='dim_airport')
    op.drop_index(op.f('ix_dim_airport_iata_code'), table_name='dim_airport')
    op.drop_index(op.f('ix_dim_airport_country'), table_name='dim_airport')
    op.drop_table('dim_airport')
    op.drop_index(op.f('ix_dim_airline_is_aggregate'), table_name='dim_airline')
    op.drop_table('dim_airline')
    # ### end Alembic commands ###
