"""agent traces and document chunks for retrieval

Revision ID: 7a71406d5f81
Revises: 905dcfde803d
Create Date: 2026-09-09 04:49:12.667406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a71406d5f81'
down_revision: Union[str, Sequence[str], None] = '905dcfde803d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_vector(bind) -> bool:
    """Is pgvector installable on this server?

    Managed Postgres offerings differ on which extensions they allow, and a
    laptop checkout may have none. Retrieval degrades to a sequential cosine
    scan over JSON-encoded vectors rather than failing to migrate, which
    keeps a fresh clone runnable with no extra system packages.
    """
    return bool(
        bind.execute(
            sa.text("SELECT count(*) FROM pg_available_extensions WHERE name = 'vector'")
        ).scalar()
    )


def upgrade() -> None:
    bind = op.get_bind()
    vector_ok = _has_vector(bind)
    if vector_ok:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run',
    sa.Column('agent_run_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('policy', sa.String(length=80), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('fallback_steps', sa.Integer(), nullable=False),
    sa.CheckConstraint('steps >= 0', name=op.f('ck_agent_run_steps_non_negative')),
    sa.PrimaryKeyConstraint('agent_run_id', name=op.f('pk_agent_run'))
    )
    op.create_index(op.f('ix_agent_run_agent'), 'agent_run', ['agent'], unique=False)
    op.create_index('ix_agent_run_started', 'agent_run', ['started_at'], unique=False)
    op.create_index(op.f('ix_agent_run_trace_id'), 'agent_run', ['trace_id'], unique=False)
    op.create_table('agent_step',
    sa.Column('agent_step_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_run_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=60), nullable=False),
    sa.Column('args', sa.Text(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('policy', sa.String(length=80), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.CheckConstraint('args !~* \'api[-_]?key\\"?\\s*[:=]\\s*\\"?(?!<redacted>)[A-Za-z0-9]{8}\'', name=op.f('ck_agent_step_no_credential_in_args')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_run.agent_run_id'], name=op.f('fk_agent_step_agent_run_id_agent_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_step_id', name=op.f('pk_agent_step')),
    sa.UniqueConstraint('agent_run_id', 'seq', name='step_order')
    )
    op.create_index(op.f('ix_agent_step_agent_run_id'), 'agent_step', ['agent_run_id'], unique=False)
    op.create_table('document_chunk',
    sa.Column('chunk_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('embed_model', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('length(content) > 0', name=op.f('ck_document_chunk_chunk_not_empty')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.source_document_id'], name=op.f('fk_document_chunk_source_document_id_source_document')),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_document_chunk')),
    sa.UniqueConstraint('source_document_id', 'seq', name='chunk_order')
    )
    op.create_index(op.f('ix_document_chunk_source_document_id'), 'document_chunk', ['source_document_id'], unique=False)
    # ### end Alembic commands ###


    if vector_ok:
        # 1024 matches Titan v2's configured output width. Vectors are stored
        # normalised, so cosine distance and inner product agree and one
        # index serves either operator.
        op.execute(
            "ALTER TABLE document_chunk "
            "ALTER COLUMN embedding TYPE vector(1024) USING embedding::vector(1024)"
        )
        # HNSW rather than IVFFlat: the corpus is small enough that build
        # time is irrelevant, and HNSW needs no training pass over data that
        # does not exist yet at migration time.
        op.execute(
            "CREATE INDEX ix_document_chunk_embedding ON document_chunk "
            "USING hnsw (embedding vector_cosine_ops)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunk_source_document_id'), table_name='document_chunk')
    op.drop_table('document_chunk')
    op.drop_index(op.f('ix_agent_step_agent_run_id'), table_name='agent_step')
    op.drop_table('agent_step')
    op.drop_index(op.f('ix_agent_run_trace_id'), table_name='agent_run')
    op.drop_index('ix_agent_run_started', table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_agent'), table_name='agent_run')
    op.drop_table('agent_run')
    # ### end Alembic commands ###
