"""add measure to the fact natural key

Revision ID: 905dcfde803d
Revises: 6a8f183cda57
Create Date: 2026-09-08 07:27:26.004785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905dcfde803d'
down_revision: Union[str, Sequence[str], None] = '6a8f183cda57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_cargo_movement', sa.Column('measure', sa.String(length=64), server_default='freight', nullable=False))
    op.drop_constraint(op.f('fact_natural_key'), 'fact_cargo_movement', type_='unique')
    op.create_unique_constraint('fact_natural_key', 'fact_cargo_movement', ['grain', 'period_id', 'airport_id', 'airline_id', 'direction', 'publisher', 'measure'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fact_natural_key', 'fact_cargo_movement', type_='unique')
    op.create_unique_constraint(op.f('fact_natural_key'), 'fact_cargo_movement', ['grain', 'period_id', 'airport_id', 'airline_id', 'direction', 'publisher'], postgresql_nulls_not_distinct=True)
    op.drop_column('fact_cargo_movement', 'measure')
    # ### end Alembic commands ###
