"""fact natural key treats nulls as equal

Revision ID: ceffe1098071
Revises: 3bf5dacdb8da
Create Date: 2026-09-08 07:23:58.705688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceffe1098071'
down_revision: Union[str, Sequence[str], None] = '3bf5dacdb8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fact_natural_key'), 'fact_cargo_movement', type_='unique')
    op.create_unique_constraint('fact_natural_key', 'fact_cargo_movement', ['grain', 'period_id', 'airport_id', 'airline_id', 'direction', 'publisher'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fact_natural_key', 'fact_cargo_movement', type_='unique')
    op.create_unique_constraint(op.f('fact_natural_key'), 'fact_cargo_movement', ['grain', 'period_id', 'airport_id', 'airline_id', 'direction', 'publisher'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
