"""HTTP serving layer.

Every endpoint compiles through the semantic layer rather than writing
its own SQL, so a metric has one definition and the dashboard and the
chat interface cannot drift apart. Endpoints are thin on purpose: they
translate URL parameters into a QuerySpec and hand back what comes out,
with its citations.
"""

from __future__ import annotations

from pathlib import Path

from fastapi import Depends, FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from sqlalchemy import text
from sqlalchemy.orm import Session

from services.api.deps import get_session
from services.api.schemas import (
    ChatRequest,
    ChatResponse,
    HealthResponse,
    QueryResponse,
)
from services.common.logging import get_logger
from services.semantic import registry
from services.semantic.compiler import QueryRejected, QuerySpec
from services.semantic.executor import run

log = get_logger(__name__)

app = FastAPI(
    title="Air Cargo Intelligence API",
    version="0.1.0",
    description=(
        "Every figure returned by this API is computed by SQL over a governed "
        "semantic layer and carries the source document behind it. No number "
        "is generated by a language model."
    ),
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# The dashboard is served by the API rather than from a separate dev
# server: it is the same origin, so there is no CORS dance, and there is
# nothing to build before it will run.
WEB_DIR = Path(__file__).resolve().parents[2] / "web"
if WEB_DIR.is_dir():
    app.mount("/static", StaticFiles(directory=WEB_DIR), name="static")

    @app.get("/", include_in_schema=False)
    def dashboard() -> FileResponse:
        return FileResponse(WEB_DIR / "index.html")


def _latest_period(session: Session, grain: str) -> str:
    """The most recent period held at this grain."""
    row = session.execute(
        text("SELECT period FROM v_cargo_fact WHERE grain = :g "
             "ORDER BY sort_key DESC LIMIT 1"),
        {"g": grain},
    ).first()
    return row[0] if row else "unknown"


def _execute(session: Session, spec: QuerySpec) -> QueryResponse:
    try:
        result = run(session, spec)
    except QueryRejected as exc:
        # A rejected query is a client error, and the message names what
        # was not recognised rather than leaking the SQL that was almost
        # built.
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return QueryResponse(**result.to_dict())


# --------------------------------------------------------------- health --

@app.get("/api/v1/health", response_model=HealthResponse, tags=["meta"])
def health(session: Session = Depends(get_session)) -> HealthResponse:
    counts = session.execute(text("""
        SELECT
          (SELECT count(*) FROM fact_cargo_movement),
          (SELECT count(*) FROM dim_airport),
          (SELECT count(*) FROM dim_airline),
          (SELECT count(*) FROM dim_period)
    """)).one()
    return HealthResponse(
        status="ok", database="connected",
        facts=counts[0], airports=counts[1], airlines=counts[2], periods=counts[3],
    )


@app.get("/api/v1/semantic", tags=["meta"])
def semantic_layer() -> dict:
    """The metric registry, so a client can discover what it may ask for."""
    return registry.describe()


# ------------------------------------------------------------- airports --

@app.get("/api/v1/airports/rankings", response_model=QueryResponse, tags=["airports"])
def airport_rankings(
    period: str | None = Query(None, description="e.g. 2026-07"),
    direction: str = Query("TOTAL", pattern="^(INTERNATIONAL|DOMESTIC|TOTAL)$"),
    country: str | None = None,
    order_by: str = Query("tonnage_mt", pattern="^(tonnage_mt|growth_yoy_pct)$"),
    min_tonnage_mt: float | None = Query(
        None,
        description="Minimum tonnage to qualify. Defaults to 100 MT when "
                    "ordering by growth, because a 4-tonne airport posting "
                    "486% is noise rather than news.",
    ),
    limit: int = Query(20, ge=1, le=200),
    session: Session = Depends(get_session),
) -> QueryResponse:
    """Airports ranked by tonnage or by year-on-year growth.

    A ranking is always scoped to one period. Without that the endpoint
    summed across every period held, so Eurostat's annual figure for
    Frankfurt (3.8m MT for a year) outranked Delhi's monthly one
    (105k MT for a month) - a league table that looks authoritative and
    compares a year against a month.
    """
    if period is None:
        period = _latest_period(session, "AIRPORT")
    filters: dict = {"grain": "AIRPORT", "direction": direction, "period": period}
    floor = min_tonnage_mt if min_tonnage_mt is not None else (
        100.0 if order_by == "growth_yoy_pct" else None
    )
    if floor:
        filters["min_tonnage_kg"] = floor * 1000.0
    if country:
        filters["country"] = country
    return _execute(session, QuerySpec(
        metrics=["tonnage_mt", "growth_yoy_pct", "source_count"],
        dimensions=["airport_iata", "airport_name", "country"],
        filters=filters, order_by=order_by, limit=limit,
    ))


@app.get("/api/v1/airports/trend", response_model=QueryResponse, tags=["airports"])
def airport_trend(
    iata: str = Query(min_length=3, max_length=3),
    direction: str = Query("TOTAL", pattern="^(INTERNATIONAL|DOMESTIC|TOTAL)$"),
    session: Session = Depends(get_session),
) -> QueryResponse:
    """One airport's series over every period held."""
    return _execute(session, QuerySpec(
        metrics=["tonnage_mt", "growth_yoy_pct"],
        dimensions=["period", "airport_iata"],
        filters={"grain": "AIRPORT", "direction": direction,
                 "airport_iata": iata.upper()},
        order_by="period", descending=False, limit=200,
    ))


# ------------------------------------------------------------- airlines --

@app.get("/api/v1/airlines/share", response_model=QueryResponse, tags=["airlines"])
def airline_share(
    direction: str = Query("TOTAL", pattern="^(INTERNATIONAL|DOMESTIC|TOTAL)$"),
    include_aggregates: bool = Query(
        False,
        description="Industry totals such as 'All Scheduled Indian Airlines'. "
                    "Off by default: summing them beside carriers double-counts.",
    ),
    limit: int = Query(20, ge=1, le=200),
    session: Session = Depends(get_session),
) -> QueryResponse:
    filters: dict = {"grain": "AIRLINE", "direction": direction}
    if not include_aggregates:
        filters["exclude_aggregate_airlines"] = True
    return _execute(session, QuerySpec(
        metrics=["tonnage_mt", "record_count"],
        dimensions=["airline_name"],
        filters=filters, order_by="tonnage_mt", limit=limit,
    ))


# ------------------------------------------------------------ anomalies --

@app.get("/api/v1/anomalies", tags=["intelligence"])
def anomalies(
    severity: str | None = Query(None, pattern="^(LOW|MEDIUM|HIGH)$"),
    grain: str | None = Query(None, pattern="^(AIRPORT|AIRLINE)$"),
    limit: int = Query(50, ge=1, le=200),
    session: Session = Depends(get_session),
) -> dict:
    """Detected anomalies, most deviant first."""
    rows = session.execute(text("""
        SELECT entity_key, COALESCE(airport_name, airline_name) AS entity_name,
               grain, direction, period,
               ROUND((observed_kg/1000)::numeric, 1) AS observed_mt,
               ROUND((expected_kg/1000)::numeric, 1) AS expected_mt,
               deviation_pct, z_score, method, severity
        FROM v_anomaly
        WHERE (CAST(:severity AS text) IS NULL OR severity = CAST(:severity AS text))
          AND (CAST(:grain AS text) IS NULL OR grain = CAST(:grain AS text))
        ORDER BY abs(deviation_pct) DESC NULLS LAST
        LIMIT :limit
    """), {"severity": severity, "grain": grain, "limit": limit}).mappings().all()
    return {"rows": [dict(r) for r in rows], "row_count": len(rows)}


@app.get("/api/v1/forecasts", tags=["intelligence"])
def forecasts(
    grain: str | None = Query(None, pattern="^(AIRPORT|AIRLINE)$"),
    horizon: int | None = Query(None, ge=1, le=12),
    limit: int = Query(50, ge=1, le=200),
    session: Session = Depends(get_session),
) -> dict:
    """Forecasts, each with its interval and the backtest error behind it."""
    rows = session.execute(text("""
        SELECT entity_key, COALESCE(airport_name, airline_name) AS entity_name,
               grain, direction, period, horizon,
               ROUND((predicted_kg/1000)::numeric, 1) AS predicted_mt,
               ROUND((lower_kg/1000)::numeric, 1)     AS lower_mt,
               ROUND((upper_kg/1000)::numeric, 1)     AS upper_mt,
               model, ROUND(backtest_mape::numeric, 1) AS backtest_mape_pct
        FROM v_forecast
        WHERE (CAST(:grain AS text) IS NULL OR grain = CAST(:grain AS text))
          AND (CAST(:horizon AS int) IS NULL OR horizon = CAST(:horizon AS int))
        ORDER BY predicted_kg DESC
        LIMIT :limit
    """), {"grain": grain, "horizon": horizon, "limit": limit}).mappings().all()
    return {"rows": [dict(r) for r in rows], "row_count": len(rows)}


# --------------------------------------------------------------- sources --

@app.get("/api/v1/sources", tags=["meta"])
def sources(session: Session = Depends(get_session)) -> dict:
    """Every ingested document and how many facts rest on it."""
    rows = session.execute(text("""
        SELECT publisher, count(*) AS documents, sum(fact_count) AS facts,
               max(retrieved_at) AS last_retrieved
        FROM v_source GROUP BY publisher ORDER BY facts DESC NULLS LAST
    """)).mappings().all()
    return {"publishers": [dict(r) for r in rows]}


# ------------------------------------------------------------------ chat --

@app.post("/api/v1/chat/query", response_model=ChatResponse, tags=["chat"])
def chat_query(
    request: ChatRequest, session: Session = Depends(get_session)
) -> ChatResponse:
    """Answer a natural-language question, grounded in stored rows.

    The question is classified and mapped onto registered metrics; it
    never becomes free-form SQL. `understood_as` is returned so a
    misreading is visible to the user rather than hidden behind a
    confident sentence.
    """
    from services.semantic.nl import answer

    try:
        result = answer(session, request.question)
    except QueryRejected as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return ChatResponse(**result)
